const UserTypes = {
  SET_CURRENT_USER : 'SET_CURRENT_USER',
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGNOUT_START: 'SIGNOUT_START',
  SIGNOUT_SUCESS: 'SIGNOUT_SUCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCESS: 'SIGNUP_SUCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

}

export default UserTypes;