const CartTypes = {
  SET_CART_STATE: 'SET_CART_STATE',
  ADD_ITEM: 'ADD_ITEM',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART:'CLEAR_CART'
}


export default CartTypes;